# Generated by Django 3.2.10 on 2023-11-27 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalBackend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(blank=True, max_length=100, null=True)),
                ('doc_spec', models.CharField(blank=True, max_length=100, null=True)),
                ('Departmentname', models.CharField(blank=True, max_length=100, null=True)),
                ('doc_image', models.ImageField(blank=True, null=True, upload_to='CategoryImage')),
            ],
        ),
        migrations.AlterField(
            model_name='depdb',
            name='Description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
