# Generated by Django 3.2.10 on 2023-11-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalBackend', '0002_auto_20231127_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='depdb',
            name='Services',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
