# Generated by Django 3.2.10 on 2023-11-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalBackend', '0003_depdb_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctordb',
            name='doc_desc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
