# Generated by Django 3.2.10 on 2023-12-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalBackend', '0004_doctordb_doc_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Testname', models.CharField(blank=True, max_length=100, null=True)),
                ('FullName', models.CharField(blank=True, max_length=100, null=True)),
                ('Description', models.CharField(blank=True, max_length=100, null=True)),
                ('testimages', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
