# Generated by Django 3.2.10 on 2023-12-05 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalBackend', '0005_labdb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labdb',
            name='FullName',
        ),
    ]
