# Generated by Django 3.2.10 on 2023-12-05 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalBackend', '0006_remove_labdb_fullname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labdb',
            name='testimages',
        ),
        migrations.AddField(
            model_name='labdb',
            name='Testimages',
            field=models.ImageField(blank=True, null=True, upload_to='Testimages'),
        ),
    ]
