# Generated by Django 3.2.10 on 2023-12-05 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalBackend', '0007_auto_20231205_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labdb',
            name='Testimages',
        ),
        migrations.AddField(
            model_name='labdb',
            name='testimages',
            field=models.ImageField(blank=True, null=True, upload_to='testimages'),
        ),
    ]
