# Generated by Django 3.2.10 on 2023-12-05 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalBackend', '0008_auto_20231205_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labdb',
            name='testimages',
            field=models.ImageField(blank=True, null=True, upload_to='CategoryImage'),
        ),
    ]
