# Generated by Django 4.2.7 on 2023-12-08 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalBackend', '0009_alter_labdb_testimages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LabDB',
        ),
    ]
