# Generated by Django 3.2.10 on 2023-11-28 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalFrontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='appoinmentDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientname', models.CharField(blank=True, max_length=100, null=True)),
                ('patientdob', models.DateField(blank=True, max_length=100, null=True)),
                ('patienttime', models.TimeField(blank=True, max_length=100, null=True)),
                ('patientnumber', models.IntegerField(blank=True, max_length=100, null=True)),
                ('patientdes', models.CharField(blank=True, max_length=100, null=True)),
                ('Departmentname', models.CharField(blank=True, max_length=100, null=True)),
                ('doc_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
