# Generated by Django 3.2.10 on 2023-11-29 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalFrontend', '0004_contactdb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactdb',
            name='subject',
        ),
    ]
