# Generated by Django 3.2.10 on 2023-11-29 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalFrontend', '0006_auto_20231129_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdb',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
