# Generated by Django 4.2.7 on 2023-12-10 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalFrontend', '0009_feedbackdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabappoDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientsname', models.CharField(blank=True, max_length=100, null=True)),
                ('patientsdob', models.DateField(blank=True, max_length=100, null=True)),
                ('patientstime', models.TimeField(blank=True, max_length=100, null=True)),
                ('patientsnumber', models.IntegerField(blank=True, null=True)),
                ('patientsdes', models.CharField(blank=True, max_length=100, null=True)),
                ('UserName', models.CharField(blank=True, max_length=100, null=True)),
                ('Testname', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
