# Generated by Django 4.2.7 on 2023-12-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalFrontend', '0010_labappodb'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoinmentdb',
            name='AppoinmentDate',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appoinmentdb',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
