# Generated by Django 4.2.7 on 2023-12-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalFrontend', '0011_appoinmentdb_appoinmentdate_appoinmentdb_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoinmentdb',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
