# Generated by Django 4.2.7 on 2023-12-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalFrontend', '0012_alter_appoinmentdb_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appoinmentdb',
            name='status',
        ),
        migrations.AddField(
            model_name='appoinmentdb',
            name='Status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
