# Generated by Django 4.2.7 on 2023-12-19 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalFrontend', '0013_remove_appoinmentdb_status_appoinmentdb_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='labappodb',
            name='Status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
