# Generated by Django 4.2.7 on 2023-12-26 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalFrontend', '0014_labappodb_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoinmentdb',
            name='patientnumber',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='contactdb',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='labappodb',
            name='patientsnumber',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
